# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1fbde363abeaf9eb9d977780ff6f758ff9bd0bef2918a576ab6816b94563cf2191e365701116a784b834fa9446a1119755219ea27698b7e428503a76de500ec0

test:
  secret_key_base: 84427520c4e4cf883efe86cfb94ec6b1791cc16851dcfac813c3dc2e67403604b923951fc0f0314cd3613c27d84c4436a004c731971cdea541d526fc90e455b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
